name: CI - Flask API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Verificar sintaxe
        run: python -m py_compile app.py
